name: Rust

on: [push]

jobs:
  unix_1:
    name: Unix Platforms
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-16.04, ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Update
        run: rustup update
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: isow
          path: target/debug/isow

  windows_2:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update
        run: rustup update
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: isow
          path: target/debug/isow.exe